apiVersion: v1
kind: Service
metadata:
  name: word-mind-master-python-service
spec:
  type: LoadBalancer
  selector:
    app: word-mind-master-python
  ports:
    - protocol: TCP
      port: 84
      targetPort: 8000

