apiVersion: v1
kind: Service
metadata:
  name: word-mind-master-ktor-service
spec:
  type: LoadBalancer
  selector:
    app: word-mind-master-ktor
  ports:
    - protocol: TCP
      port: 85
      targetPort: 8000

