apiVersion: v1
kind: Service
metadata:
  name: word-mind-master-postgres-service
spec:
  type: LoadBalancer
  selector:
    app: word-mind-master-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

